name: RohitWordpress
description: |
  # Description of the Catalog Entry
version: 0
category: # Category to be used for searching catalog entries
maintainer: Rohit Deshmukh
license: # The license
projectURL: # A URL related to the catalog entry
