version: '2'
services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    stdin_open: true
    tty: true
    links:
    - mysql:mysql
    ports:
    - 8080:80/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: name=wordpress
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    stdin_open: true
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: name=mysql
