.catalog:
  name: Wordpress
  version: 0
  description: # Description of the versioned template of the Catalog Entry
  uuid: 1
  minimum_rancher_version: 1.3.1
  questions: #Used to request user input for configuration options
  wordpress:
    scale: 1
    start_on_create: true
  mysql:
    scale: 1
    start_on_create: true
