.catalog:
  name: Wordpress
  version: 0
  description: # Description of the versioned template of the Catalog Entry
  uuid: 1
  minimum_rancher_version: 1.3.1
  questions: 
    - variable: "WORDPRESS_DB_PASSWORD"
      description: "Wordpress Password"
      label: "Wordpress Root password:"
      required: true
      type: "string"
    - variable: "WORDPRESS_DB_USER"
      description: "Wordpress user"
      label: "Wordpress Root user:"
      required: true
      type: "string"
    - variable: "MYSQL_DATABASE"
      description: "Database name"
      label: "MYSQL DATABASE:"
      required: true
      type: "string"
    - variable: "MYSQL_PASSWORD"
      description: "MYSQL_PASSWORD"
      label: "MYSQL_PASSWORD:"
      required: true
      type: "string"
    - variable: "MYSQL_ROOT_PASSWORD"
      description: "MYSQL_ROOT_PASSWORD"
      label: "MYSQL_ROOT_PASSWORD:"
      required: true
      type: "string"
    - variable: "MYSQL_USER"
      description: "MYSQL_USER"
      label: "MYSQL_USER:"
      required: true
      type: "string"
  wordpress:
    scale: 1
    start_on_create: true
  mysql:
    scale: 1
    start_on_create: true
